### PR TITLE
autoGodzamok, autoSL & autoRigidel

### LINKED ISSUE #18: Sugar Lump Harvesting
I turned on SL harvesting for a little bit while a bifurcated lump was MATURE, but not ripe. Frozen Cookies immediately botched the harvest.

### PR DESCRIPTION
**Pull request by Mtarnuhal**
Fix #18 autoSL + autoRigidel bug where sugar lumps were collected to quickly
autoGodzamok Sane & Insane options Restored

### CODE REVIEW

**Review by adavidw — COMMENTED** [review]
Just to clarify, with autoGodz, your intent is that nothing will be rebought unless you have it in insane mode, correct?

Here's the three behaviors as coded in this PR:

1. Sell the cursors and farms. Don't buy any more. If more cursors and farms appear during the devastation buff (like from user purchases or auto buy) sell those too.
2. Sell the cursors and farms. Don't buy any more. Don't do anything else during the devastation buff. If more cursors and farms appear during the devastation buff (like from user purchases or auto buy) nothing will happen to those.
3. Sell the cursors and farms. Rebuy the amount that was sold. Repeat continuously during the buff.

Is that the intent for all?

As an aside, I actually completely rewrote AutoGodz in my dev branch to auto calculate whether there would be a positive payoff based on the current click rate, then to auto-cycle buying and selling just cursors in smaller amounts (1/10 of the actual initial sale) to jack up the buff before buying them all back at the end.

It's not quite ready for a PR, though, because I'm still tweaking to get the right balance between wanting it to be net positive all the time and making sure it's getting the highest buff. Take a look, though, if you want to see what I'm doing.

**Comment by Mtarnuhal** [comment]
The Intent of autoGodz is to trigger on Clickfrenzies or Dragonflight.
Selling all of the cursors and farms.
Normal mode it will keep selling them no matter what. which is not ideal.
Sane mode stops selling them if devastation is active. It will sell again if Clickfrenzie or Dragonflight is still active.
Insane mode will quickly sell and buy the sold amount. Which is ridiculous and should not be used.

I think Sane mode is what should be kept in the code.

I've just checked and selling the farms doesn't increase the percentages on the buff.
Selling 500 cursors and 500 farms gives me a 500% buff and selling only 500 cursors also gives me a 500% buff.

As of your rewrite autoGodz looks promising I'm looking forward to a finished version.
I think it's best to wait till you finished then with the rewrite of the autoGodz.

Maybe we should setup a discord to discuss certain behaviors of the game and the intended code of Frozencookies

**Comment by adavidw** [comment]
Yeah, I'm up for a Discord or something. In terms of intended behavior, I don't see much need for the three modes. For the moment, let's ignore my experiments in maximizing gain. If I wasn't doing that, here's how I think I would do it (to keep it as simple as possible:

- AutoGodz has one mode, and it's either off or on
- If AutoGodz is on and a click buff is active, but Devastation is NOT active:
  - sell the cursors and farms
  - then, if autoBuy is turned on, the user has already signaled their intent to have things purchased for them, so rebuy what you sold (up to the limit if any limit is set). Otherwise, don't rebuy anything.

And are you sure about the farms not adding to the bonus? The graphic on screen won't update, but when you call Game.buffs["Devastation"].multClick after selling some more buildings, the value is added.

**Comment by Mtarnuhal** [comment]
Ok i'll setup a discord for the development of this addon. ill update it on readme.md when ready.

I totally agree with you to keep it as simple as possible.
annoying that it doesn't update the graphics.
with Game.buffs["Devastation"].multClick I was seeing an increase when selling more buildings.
6 for 500 cursors and 11 for 500 cursors and 500 farms.

I'll make the necessary changes.

**Comment by Mtarnuhal** [comment]
Just to clarify further.

- If AutoGodz is on and a click buff is active, but Devastation is NOT active:
  - sell the cursors and farms
  - then, if autoBuy is turned on, the user has already signaled their intent to have things purchased for them, so rebuy what you sold (up to the limit if any limit is set). Otherwise, don't rebuy anything.

Should the bought buildings be sold because Devastation is active? to gain more as seen in Game.buffs["Devastation"].multClick
OR
Should the bought buildings **not** be sold because Devastation is active?

**Comment by adavidw** [comment]
For the duration of that one devastation buff, there should be no more further selling of buildings.

If buildings were sold (triggering a buff), then rebought, everything just sits there for the duration of the ten seconds. When that's expired, if there's still a dragon flight or click frenzy active, the cycle might repeat.

This mimics the "sane" mode of the previous implementation as far as I know just with the added bit of buying the buildings back in one bunch if auto buy is already on, rather than waiting for auto buy to buy them back one at a time (as would happen if the autogodz function didn't do the buying.

**Review by adavidw — CHANGES_REQUESTED** [review]
Since you left 1 farm behind when selling the farms. buying `farmMax` farms in line 2200 will end up with one farm over the limit. Should probably be
`safeBuy( Game.Objects['Farm'], FrozenCookies.farmMax - 1 );`

**Comment by Mtarnuhal** [comment]
> Since you left 1 farm behind when selling the farms. buying `farmMax` farms in line 2200 will end up with one farm over the limit. Should probably be
> `safeBuy( Game.Objects['Farm'], FrozenCookies.farmMax - 1 );`

Yeah true but this way you get the full 500% potential instead of the 490% you would get if you sold 499 farms

**Comment by Mtarnuhal** [comment]
We should also take a look at the recommendation list cause it is getting out of wack due to the limit on the cursors, farms, and wizard towers.
image

**Review by adavidw — COMMENTED** [review]
You have to look at the limit that's set because otherwise you'll way overbuy. If I have 300 cursors when AutoGodz kicks in, but a limit of 500 cursors, this way it will try to buy 500 cursors after selling.

Should probably check both things though, because I think you might be able to have a limit number set, but have the ability to use the limit turned off. Here's what I was using before:
```
            if ( FrozenCookies.autoBuy == 1 ) {
                if (Game.Objects.Cursor.amount < 10) {
                    if ((FrozenCookies.cursorLimit) && countC > FrozenCookies.cursorMax) {
                        safeBuy(Game.Objects['Cursor'], FrozenCookies.cursorMax);
                        logEvent("AutoGodzamok", "Bought " + FrozenCookies.cursorMax + " cursors");
                    } else {
                        safeBuy(Game.Objects['Cursor'], countC);
                        logEvent("AutoGodzamok", "Bought " + countC + " cursors");
                    }
                }

                if (Game.Objects.Farm.amount < 10) {
                    if ((FrozenCookies.farmLimit) && countF > (FrozenCookies.farmMax - 1)) {
                        safeBuy(Game.Objects['Farm'], FrozenCookies.farmMax - 1);
                        logEvent("AutoGodzamok", "Bought " + (FrozenCookies.farmMax - 1) + " farms");
                    } else {
                        safeBuy(Game.Objects['Farm'], countF);
                        logEvent("AutoGodzamok", "Bought " + countF + " farms");
                    }
                }
            }
```

And to your other point, the buff multiplier is set when the buildings are sold, so buying an extra one would only help on the next buff, not the current one. And each building is only +1%, so buying the extra one would give you +500% instead of +499%, which translates to a `multClick` value on the buff of `6` instead of `5.99`. Not a significant difference, and it would look to the user to be an error if they started the click frenzy/dragonflight with 500 farms and ended with 501.

**Comment by Mtarnuhal** [comment]
For some reason, I was thinking about every 10 buildings = 1%.
Also, I don't think you need to check if the building is under 10. 
This just makes it an extra unnecessary step.

**Comment by adavidw** [comment]
That <10 thing was in the code before, so I left it as an extra check in case the sell failed and the cursors/farms didn't actually get down that low. If the sell failed, you'd essentially double your existing cursors/farms.

I don't know if it's possible for the sell to fail, though. Sure, a buy can fail if you don't have cookies in the bank, but is there any scenario where a sell can fail? I can't think of one, so you're probably right that it's pointless.

**Pull request merged**
