### PR TITLE
old sell values update

### PR DESCRIPTION
**Pull request by geojak**
choc egg value updated

### CODE REVIEW

**Comment by Mtarnuhal** [comment]
Where did you find these new values?

**Comment by geojak** [comment]
patch 2.0109 http://cookieclicker.wikia.com/wiki/Update_History. there was a buy and selling strategy involving cheapcaps which allowed to sell for more than what you payed if you freeze the garden. it was said to very easily without cheating get to infinity cookies. so orteil changed it

**Comment by geojak** [comment]
it was first introduced in 2.0107(beta)

**Comment by geojak** [comment]
forgot to change one value of 0.85 below

**Pull request merged**
