### PR TITLE
Queenbeet nerf accounted in garden bank

### PR DESCRIPTION
**Pull request by geojak**
6% went down to 4% in patch 2.016

### CODE REVIEW

**Comment by geojak** [comment]
by the way, i have spread the word on discord. maybe someone (other than me) is going to start using your updated fork soon

**Comment by Mtarnuhal** [comment]
It would be nice to keep one fork up to date rather than keeping track of multiples.

**Comment by geojak** [comment]
i deleted my fork of yours

**Comment by geojak** [comment]
kisslab69 above your fork has also started to push some updates. so far he also exluded turning shimmering veil on as you have. he also exluded turning shimering veil off and turning golden switch off, but i think that is unneeded.

**Pull request merged**
