### PR TITLE
low fps option added

### PR DESCRIPTION
**Pull request by geojak**
added very low fps option. usefull to let the game run "slower" to save cpu performance and fight overheating.

### CODE REVIEW

**Comment by geojak** [comment]
i should have added them into one pull reqeust. i accidentally opened a seperate pull reuqest for each file that is affected

**Comment by Mtarnuhal** [comment]
Could you try this minified version?
https://cdn.jsdelivr.net/gh/Mtarnuhal/FrozenCookies@0361ca6044826bcd313de7c3812634f2125e3edf/frozen_cookies.min.js
It's without the added lowered FPS option.

**Comment by geojak** [comment]
i have loaded the minified version and it runs without error (the fps change is not included, so i can be sure i loaded it up properly), but i do not understand to code well enough to comment any further

**Comment by Mtarnuhal** [comment]
The code is smaller to load so it should load faster. Performance wise I don't think it has much of an impact.
But I can't say that for sure since my pc is way to powerful to even notice a difference.

**Comment by geojak** [comment]
I have ascended now and am trying out if autobuy and logics still work. So far nothing special. I did compare the old and new version a bit with task manager to see if their is a visible difference in memory or cpu but it is insignificant to the plain eye.

I have noticed that autobuy stopped switching seasons by itself to unlock all missing seasonal upgrades. Might be related to the new price of the switches. Needs further testing

Sent from Mail for Windows 10

**Pull request merged**
